[package]
name = "trust-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
cedar-policy = { workspace = true }
walkdir = { workspace = true }
similar = { workspace = true }
ureq = { workspace = true, optional = true }
dirs = { workspace = true, optional = true }
sherpa-rs = { workspace = true, optional = true }
cpal = { workspace = true, optional = true }
hound = { workspace = true, optional = true }
bzip2 = { workspace = true, optional = true }
tar = { workspace = true, optional = true }

[dev-dependencies]
uuid = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
tempfile = "3"

[features]
default = []
voice = ["dep:sherpa-rs", "dep:cpal", "dep:hound", "dep:ureq", "dep:dirs", "dep:bzip2", "dep:tar"]
